displayName=Spell Helper
author=1Defence
description=Prevents misclicks on limited spells(xfer,potshare,heal other,telegrab)
tags=spells,alting,misclick,cast,helper,goats,potshare,xfer,energy transfer,heal other,ps,tg,telegrab
version=1.0.0
plugins=com.spellhelper.SpellHelperPlugin
build=standard